### ISSUE TITLE
Dependency conflict when installing AlignScore

### ISSUE THREAD

**Issue by PrLeung** [xiaowu0162/sync-ralm-faithfulness#2]
I have setup environment for syncheck successfully  on a Linux machine with CUDA 12.1. However, when I tried to install AlignScore following [Installation](https://github.com/yuh-zha/AlignScore?tab=readme-ov-file#installation), dependecies conflits. I wonder whether you encountered this problem and wanna know how you solved it. Thank you very much!

**Comment by xiaowu0162** [comment]
You may install alignscore with `--no-deps`.
