### ISSUE TITLE
Module "backtrack_detection.lid" is not found

### ISSUE THREAD

**Issue by PrLeung** [xiaowu0162/sync-ralm-faithfulness#3]
When I tried to run fod.sh, an error occurs:
`Traceback (most recent call last):
  File "sync-ralm-faithfulness/decoding/decode.py", line 13, in <module>
    from backtrack_detection.lid import compute_lid
ModuleNotFoundError: No module named 'backtrack_detection.lid'`
I would appreciate it if you could solve this issue. Thank you very much!

**Comment by xiaowu0162** [comment]
Thank you for raising the issue. We have added `lid.py` under `backtrack_detection`.

**Comment by PrLeung** [comment]
I found some errors in lid.py, such as line 110: true_pds is not defined.

**Comment by xiaowu0162** [comment]
Hi @PrLeung ,

Thank you for catching this. This implementation was shared by the original author of the ICML 2024 paper. Our method does not depend on the function `other_ids` and only uses the `compute_lid` function.

**Comment by PrLeung** [comment]
Thanks for your response!
