### ISSUE TITLE
Could not find input files of bio, famous-100 and famous-100-anti-v2

### ISSUE THREAD

**Issue by PrLeung** [xiaowu0162/sync-ralm-faithfulness#5]
Hi, I could not find input files below though I have extracted all tar.gz files:
data/instance_level/factscore_unlabeled_alpaca_13b_retrieval.jsonl
data/instance_level/famous_people_100_with_wiki.jsonl
data/instance_level/famous_people_100_with_anti_wiki_v2.jsonl

**Comment by xiaowu0162** [comment]
Hi @PrLeung ,

They should be inside `data/instance_level/data_instance_level.tar.gz`.
